#!/usr/bin/env bash

cd "$(dirname "$0")" &&
    docker compose down --remove-orphans &&
    docker compose build --no-cache &&
    docker compose up --detach --wait --wait-timeout 120 &&
    open http://localhost:3000